# Generated by Django 3.2 on 2022-07-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0002_remove_employee_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='clent_name',
            new_name='client_name',
        ),
    ]
