# Generated by Django 3.2 on 2022-07-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0003_rename_clent_name_testimonials_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='name',
        ),
    ]
