# Generated by Django 3.2 on 2022-07-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0004_remove_testimonials_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='superviser',
            name='superviser_contact',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
