# Generated by Django 3.2 on 2022-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0005_superviser_superviser_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/career')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
