# Generated by Django 3.2 on 2022-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0009_auto_20220811_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
